### ISSUE TITLE
jurassic 2.2.0 doesn't work in 4.6 runtime when running handlebars.js

### ISSUE THREAD

**Issue by nkwinder** [paulbartrum/jurassic#1]
When using the latest nuget package (2.2.0): 
 
`var scriptEngine = new ScriptEngine();
var hpath = Server.MapPath("~/scripts/handlebars-v2.0.0.js");
scriptEngine.ExecuteFile(hpath);
scriptEngine.Execute(@"var precompile = Handlebars.precompile;");

var html = "this is a sample template {{variable}}";
result = scriptEngine.CallGlobalFunction("precompile", html).ToString();`

The above code results in: **Common Language Runtime detected an invalid program**.
This happens only when running on ASP.NET Version:4.6.1055.0. Worked in previous asp.net versions.

I compiled from the latest source and the problem is now gone. 
Maybe its a good idea to publish a new package?

thank you

**Comment by paulbartrum** [comment]
This is likely due to the codegen bug that was fixed in commit 42d647abd511169122a2837184369b12ebfa27f4.  I would like to publish the fix as a nuget package update, but unfortunately I don't have ownership over any of the various jurassic nuget packages.  I've sent off a few emails in an attempt to get access to these projects (no luck yet).  If that doesn't work I'll have to create a new package.  It's a bit up in the air at the moment.

**Comment by paulbartrum** [comment]
Okay, I have published an update to the Jurassic nuget package that has this fix.

https://www.nuget.org/packages/Jurassic/

**Comment by nkwinder** [comment]
Thank you very much!
