### ISSUE TITLE
Jurassic.dll not strong named signed

### ISSUE THREAD

**Issue by mdahamiwal** [paulbartrum/jurassic#17]
Hi Paul,

I see few threads around this but still don't find the strong named signed binary at http://nuget.org. I am using this in a project that uses strong name signing and has lot of dependencies on other projects. Can you refresh the nuget package with a signed binary?

**Comment by mdahamiwal** [comment]
@paulbartrum, ping

**Comment by paulbartrum** [comment]
I plan to strong name the upcoming version 3 release (but when that'll happen is anyone's guess!)  I'm a bit hesitant to strong name the current version because I'm worried that it might break existing users.  Specifically I'm worried about the binding redirect issues documented here: https://github.com/dotnet/corefx/blob/master/Documentation/project-docs/strong-name-signing.md

Can you sign it yourself?  Here's the 2.2 release tag: https://github.com/paulbartrum/jurassic/releases/tag/v2.2

**Comment by mdahamiwal** [comment]
Self-signing will hinder me to take nuget.org dependency for all nuget packages in my project and I don't want to make an exception for Jurassic.dll. Just a small clarification:

Won't you break the existing users if you strong name the future version and push it to nuget.org since all the existing users will end up getting the latest release? If that is the not the case, can you push a strong named version changing the patch version for V.2.2 (2.2.2)? 

Another way to avoid users getting the latest strong binary: you can create another package with a prerelease version for 2.2.1, something like 2.2.1-strongnamed. As nuget considers 2.2.1-strongnamed as lower than 2.2.1, it won't break anyone i guess.
