### ISSUE TITLE
Switch Target Framework version to .NET 4.5 / 4.5.2

### ISSUE THREAD

**Issue by kpreisser** [paulbartrum/jurassic#43]
Hi,
I saw that the target .NET Framework for Jurassic was [changed from 3.5 to 4.0](https://github.com/paulbartrum/jurassic/commit/e59ac6e01680506ecdb7759c0f605d3ec0577d1a#diff-f055085fa87440d4dccb612c44d26269R13).

However, according to [Microsoft .NET Framework Support Lifecycle Policy FAQ](https://support.microsoft.com/en-us/gp/framework_faq/en-us), Support for .NET 4.0, 4.5 and 4.5.1 has ended at January 12, 2016.

Therefore, I think it makes sence to not only switch to 4.0 but instead to 4.5 (or even 4.5.2).
Thanks!

**Comment by paulbartrum** [comment]
I needed to switch to v4.0 because that's the first version that has the `ConditionalWeakTable` class.  Is there any benefit for a class library to switch to v4.5?

**Comment by T917820981726** [comment]
Hi,
If there is currently no need to use a type that is available in v4.5 or higher, then there is no immediate benefit in switching to v4.5.
My thinking was, since this is going to be a new major version (Jurassic 3.0) where a higher .NET version than v3.5 is required anyway (with using of the ConditionalWeakTable), it might make sense to switch to v4.5 instead of to v4.0, because then if in the lifetime of the Jurassic 3.0 version a change or new feature is required that is only available in v4.5, you can just start using it (and if someone has the v4 CLR installed, we can except the BCL to be at least v4.5.2 as this is the minimum supported version).

However, of course it is up to you if you want to make that change, I can live with the library targeting v4.0. :-)

**Comment by kpreisser** [comment]
I'm closing this issue as Jurassic now targets .NET Standard 2.0.
