### ISSUE TITLE
Date.valueOf() not standard compliant

### ISSUE THREAD

**Issue by Ablu** [paulbartrum/jurassic#65]
Hello,

we realized that the valueOf() method of an date instance returns a floating point number. The Browser implementations of JavaScript do return integer values.

[The ECMA Script standard](http://www.ecma-international.org/ecma-262/6.0/#sec-time-values-and-time-range) specifies that a time only is precise to milliseconds. Jurassic seems to use the TotalMilliseconds property of C# (https://github.com/paulbartrum/jurassic/blob/master/Jurassic/Library/Date/DateInstance.cs#L905) which returns a higher precision.

This way the following code will lead to stripping the milliseconds:
~~~js
var newDate = new Date(otherDate.valueOf());
newDate.setDate(otherDate.getDate() + days);
~~~

The result Date will not be exactly `days` days in the future. There will be a slight difference due to the millisecond fractions.

Regards,
Ablu

**Comment by paulbartrum** [comment]
Thanks for the well written bug report :-)

**Comment by kpreisser** [comment]
Hi,

I'm wondering if using `Math.Round()` with the `DateTime.TotalMilliseconds` is the correct way to convert the `DateTime` into "JavaScript-Time" (Unix Time in Milliseconds).

Consider the following DateTime example:
```c#
var myDate = new DateTime(2016, 1, 1, 11, 59, 59, 999, DateTimeKind.Utc);
myDate = myDate.AddTicks(9999); // Ticks = 635872463999999999

Console.WriteLine(myDate.ToString("o"));
Console.WriteLine("Raw:    " + myDate.ToUniversalTime().Subtract(new DateTime(1970, 1, 1, 0, 0, 0, DateTimeKind.Utc)).TotalMilliseconds);
Console.WriteLine("Round:  " + Math.Round(myDate.ToUniversalTime().Subtract(new DateTime(1970, 1, 1, 0, 0, 0, DateTimeKind.Utc)).TotalMilliseconds));
Console.WriteLine("Unix:   " + new DateTimeOffset(myDate).ToUnixTimeMilliseconds());
Console.WriteLine("Unix2:  " + (myDate.Ticks / TimeSpan.TicksPerMillisecond 
    - new DateTime(1970, 1, 1, 0, 0, 0, DateTimeKind.Utc).Ticks / TimeSpan.TicksPerMillisecond));
```

This represents the Date `2016-01-01T11:59:59.9999999Z`. When running the program, it prints:
```
2016-01-01T11:59:59.9999999Z
Raw:    1451649600000
Round:  1451649600000
Unix:   1451649599999
Unix2:  1451649599999
```

This means `DateTime.TotalMilliseconds` in this case gives `1451649600000` which however is too high, because `new Date(1451649600000)` prints in Chrome `2016-01-01T12:00:00.000Z`.

When using the .NET 4.6 method `DateTimeOffset.ToUnixTimeMilliseconds());` however, the result is `1451649599999` which displays `2016-01-01T11:59:59.999Z` which should be more correct. (The value of "Unix2" is calculated in the same way).

Also e.g. when using `1969-12-31T23:59:59.9999999Z` (Ticks: `621355967999999999`), the output is:
```
1969-12-31T23:59:59.9999999Z
Raw:    -0.0001
Round:  0
Unix:   -1
Unix2:  -1
```
In that case TotalMilliseconds returns a fractional value, but the Round method converts it to `0` which is also not correct, as the correct value would be `-1`.

What do you think?

Thanks!

**Comment by Ablu** [comment]
Thanks for the super fast response... Though @kpreisser's concerns look valid...

Regards,
Ablu

**Comment by paulbartrum** [comment]
The reason I used `Math.Round` is simple: it minimizes the error (±0.5ms).  Using `Floor` would mean the error would be up to 1ms.  I'm not sure why it's important to match the behaviour of `ToUnixTimeMilliseconds`?

**Comment by kpreisser** [comment]
Hi @paulbartrum,

as I mentioned in the PR, when you you do `new Date()` in JS, it could happen that you get a date like `2016-01-01T11:59:59.9999999Z`.
In that case, `date.toUTCString()` displays `Fri, 01 Jan 2016 11:59:59 GMT`, but `new Date(date.getTime()).toUTCString()` displays `Fri, 01 Jan 2016 12:00:00 GMT`.

This doesn't look correct to me, because
- the two expressions return different result althouths they should be the same internal JS time value,
- the second expression says it's already `12:00:00` although that's not true - it's still `11:59:59` (and a few milliseconds/nanoseconds).

You say you used Round() because it minimizes the error. While this is can be done for numeric values, I don't think it can be done for time values. Imagine you need to convert the DateTime to a value not in milliseconds but in minutes, for a system that displays `hh:mm`. Now, if it is **08:23:46.412**, does this system then display **08:24** because the error is only ~0,22? Or does it display **08:23** until the time is actually >= **08:24:00.000** before it displays **08:24** (althouth the error is ~0.77)?
I think it's the latter one ;-)
![datetime-clock](https://cloud.githubusercontent.com/assets/13289184/19756784/4d41050a-9c1f-11e6-8d96-978295f8c3e2.png)

Therefore I think the same behavior should be true with Jurassic (which aligns with `DateTimeOffset.ToUnixTimeMilliseconds()`).

Thanks!

**Comment by paulbartrum** [comment]
Sorry, I only skimmed the PR and didn't realize that the substance of the argument was different in the PR compared to the above argument.  Yes, you're right, `date.toUTCString()` should equal `Date(date.getTime()).toUTCString()`, and yes, rounding down is better for digital clock-type applications.  Okay, you've convinced me, I'll change it.
