### ISSUE TITLE
Is it possible to make http requests?

### ISSUE THREAD

**Issue by rodrigoroma** [paulbartrum/jurassic#67]
Hi, 

would it be possible to make an http request using only the Jurassic's javascript code?

I know i can call a .NET method from JavaScript that could handle this for me but I wanna know if there is a "direct way" to do this.

Thanks!

**Comment by MaitreDede** [comment]
Hi,

There is no method out of the box to make http calls. You have to write a bit of C# to expose a javascript function that will make the request.

Based on https://github.com/paulbartrum/jurassic/wiki/Calling-a-single-.NET-method-from-JavaScript :
```
engine.SetGlobalFunction("callHttp", new Func<string, int>((url)=>{
//Http request implementation
}));
```

In my case, I have developped a XMLHttpRequest implementation, following this guide : https://github.com/paulbartrum/jurassic/wiki/Exposing-a-.NET-class-to-JavaScript

**Comment by rodrigoroma** [comment]
Thanks for the answer!

Exposing a .NET class to JS instead of calling a single .NET method is an interesting solution.

Could you provide your XMLHttpRequest implementation?

**Comment by MaitreDede** [comment]
Due to the "async" nature of requests made by `XMLHttpRequest`, my implementation works with the implementation I have made of `setTimout`, `setImmediate`, and the `Promise` (see https://github.com/paulbartrum/jurassic/issues/54).

I don't want to support/implement "sync" requests.  (see https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest/open).

It works with a vanilla Jurassic, but it is not an "easy" solution.

When I have time, I will make a working sample.

In the mean time, here is a sample way to make http requests with a simple function (not tested) :

        public string MakehttpGetAsAstring(ScriptEngine engine, string url)
        {
            HttpWebRequest request = WebRequest.CreateHttp(url);
            request.Method = "GET";
            var iar = request.BeginGetResponse(null, null);
            HttpWebResponse response = (HttpWebResponse)request.EndGetResponse(iar);
            if (response.StatusCode == HttpStatusCode.OK)
            {
                using (StreamReader sr = new StreamReader(response.GetResponseStream()))
                {
                    return sr.ReadToEnd();
                }
            }
            else
            {
                //TODO throw new JavascriptException(engine);
                throw new Exception();
            }
        }

And register it with the engine : 

            engine.SetGlobalFunction("getHttpString", new Func<string, string>((url) => {
                return MakehttpGetAsAstring(this, url);
            }));

**Comment by rodrigoroma** [comment]
Thanks again! My current solution to make HTTP requests is similar to yours.

Now I'll take a look at #54 because doing this in a async way is interesting to me.
