### ISSUE TITLE
bignumber.js is not working properly under Jurassic

### ISSUE THREAD

**Issue by nekobul** [paulbartrum/jurassic#73]
http://jsfromhell.com/classes/bignumber is not working properly.

Try to execute the following code under Jurassic:

**var numMinusOne = new BigNumber("129963294281830401").substract(1).toString();**

Expected behavior:

numMinusOne variable should contain 129963294281830400.

Observed behavior:

numMinusOne  variable contains NaN.

-----------------------

Additional information. Try to execute the same code under IE or Chrome. It will work fine.

**Comment by paulbartrum** [comment]
Sorry for the delay.  I tracked this down to incorrect code-gen in the assignment operator.

A statement like this:
```
x = '123'; (x = ['123'])[0] = x[0]
```
should evaluate the left-hand side before the right-hand side, but Jurassic does the opposite.  I'll check in a fix soon.

**Comment by nekobul** [comment]
Paul,

I have suspected there was an issue with the evaluation order. I was wondering why this was not caught in the JavaScript compatibility tests? If not included, this might be a good candidate for inclusion for future regression testing.

Let us know when and where you make the fix. Thank you for your efforts!

**Comment by paulbartrum** [comment]
This wasn't caught in my unit test suite because it's really quite subtle.  Just check out the example above -- it's not exactly something people would normally write :-)

The line of code that failed in BigNumber.js was this one:
```js
o._f = ((n = n.replace(/[^\d.]/g, "").split(".", 2))[0] = n[0].replace(/^0+/, "") || "0").length;
```

If you were referring to the ES6 test suite -- Jurassic fails a bunch of these tests, so I'm guessing it's one of those.
